version: '3.8'
services:
  ecommerce-flask-stripe:
    container_name: express
    restart: always
    build: './ecommerce-flask-stripe'
    ports:
      - "7000:7000"
    networks:
      - load-balancer
networks:
  server_load_balancer:
    external: true

    #ports:
    #  - "7000:7000"
    # networks:
    #  - web_network
#networks:
#  web_network:
#    driver: bridge

